# Generated by Django 5.2.12 on 2026-03-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('post_type', models.CharField(choices=[('news', 'News'), ('event', 'Event')], default='news', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_events/')),
                ('posted_as', models.CharField(choices=[('news', 'News'), ('event', 'Event')], default='news', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News & Event',
                'verbose_name_plural': 'News & Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
